knp_snappy:
    pdf:
        enabled:    true
        # binary:     '%env(WKHTMLTOPDF_PATH)%'
        binary:        "\"C:\\Program Files\\wkhtmltopdf\\bin\\wkhtmltopdf.exe\""
        options:                         
                    enable-local-file-access: true
    image:
        enabled:    true
        binary:     '%env(WKHTMLTOIMAGE_PATH)%'
        options:    []
